"""Initial migration with current models posts2

Revision ID: 02c333317558
Revises: 9b55d61c8e56
Create Date: 2025-02-03 15:04:24.064372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02c333317558'
down_revision = '9b55d61c8e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
