"""Initial migration with current models Modules

Revision ID: 0a99b7a1d545
Revises: bbd4c1cf2dee
Create Date: 2025-01-30 08:45:00.944332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a99b7a1d545'
down_revision = 'bbd4c1cf2dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('settings_schema', mysql.JSON(), nullable=False),
    sa.Column('templates', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('module_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('settings', mysql.JSON(), nullable=False),
    sa.Column('content', mysql.JSON(), nullable=True),
    sa.Column('selected_template', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('module_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_instances_module_id'), ['module_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_instances_module_id'))

    op.drop_table('module_instances')
    op.drop_table('modules')
    # ### end Alembic commands ###
