"""Initial migration with current models baner

Revision ID: 203d66cb9673
Revises: b8ce206d5460
Create Date: 2025-02-01 11:46:15.527182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203d66cb9673'
down_revision = 'b8ce206d5460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_instance_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('cards_in_row', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_instance_id'], ['module_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banner_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banner_instances_module_instance_id'), ['module_instance_id'], unique=False)

    op.create_table('banner_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('banner_id', sa.Integer(), nullable=False),
    sa.Column('background_image_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('link_text', sa.String(length=255), nullable=True),
    sa.Column('link_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['background_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['banner_id'], ['banner_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banner_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banner_items_banner_id'), ['banner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banner_items_banner_id'))

    op.drop_table('banner_items')
    with op.batch_alter_table('banner_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banner_instances_module_instance_id'))

    op.drop_table('banner_instances')
    # ### end Alembic commands ###
