"""Remove unique constraint from ProductVariation SKU

Revision ID: 2e33f57d70a4
Revises: a34bb4914793
Create Date: 2025-07-23 18:49:09.896049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e33f57d70a4'
down_revision = 'a34bb4914793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variations_sku'))
        batch_op.create_index(batch_op.f('ix_product_variations_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variations_sku'))
        batch_op.create_index(batch_op.f('ix_product_variations_sku'), ['sku'], unique=True)

    # ### end Alembic commands ###
