"""Add custom_css_class and target_blank to MenuModuleInstance

Revision ID: 364945993833
Revises: 4fc7af82dbc6
Create Date: 2025-07-25 11:33:34.315878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364945993833'
down_revision = '4fc7af82dbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_css_class', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('target_blank', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_instances', schema=None) as batch_op:
        batch_op.drop_column('target_blank')
        batch_op.drop_column('custom_css_class')

    # ### end Alembic commands ###
