"""Update banner module to slidebanner functionality

Revision ID: 3bbc913e5e61
Revises: 25c5762d5ee1
Create Date: 2025-08-08 09:46:05.244461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bbc913e5e61'
down_revision = '25c5762d5ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала удаляем foreign key constraints
    with op.batch_alter_table('slidebanner_items', schema=None) as batch_op:
        batch_op.drop_constraint('slidebanner_items_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('slidebanner_items_ibfk_2', type_='foreignkey')
        batch_op.drop_index('ix_slidebanner_items_banner_id')

    op.drop_table('slidebanner_items')
    
    with op.batch_alter_table('slidebanner_instances', schema=None) as batch_op:
        batch_op.drop_constraint('slidebanner_instances_ibfk_1', type_='foreignkey')
        batch_op.drop_index('ix_slidebanner_instances_module_instance_id')

    op.drop_table('slidebanner_instances')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slidebanner_instances',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('module_instance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('cards_in_row', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_instance_id'], ['module_instances.id'], name='slidebanner_instances_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('slidebanner_instances', schema=None) as batch_op:
        batch_op.create_index('ix_slidebanner_instances_module_instance_id', ['module_instance_id'], unique=False)

    op.create_table('slidebanner_items',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('banner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('background_image_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('link_text', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link_url', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['background_image_id'], ['images.id'], name='slidebanner_items_ibfk_2'),
    sa.ForeignKeyConstraint(['banner_id'], ['slidebanner_instances.id'], name='slidebanner_items_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('slidebanner_items', schema=None) as batch_op:
        batch_op.create_index('ix_slidebanner_items_banner_id', ['banner_id'], unique=False)

    # ### end Alembic commands ###