"""Initial migration with current models Site settings

Revision ID: 3e52a4651772
Revises: 92b0c5701192
Create Date: 2025-02-06 18:11:14.002704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e52a4651772'
down_revision = '92b0c5701192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_settings_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'site_settings', ['site_settings_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('site_settings_id')

    # ### end Alembic commands ###
