"""Initial migration with current models Site settings

Revision ID: 427e0622256a
Revises: aba4625da5f1
Create Date: 2025-02-06 12:38:42.285609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427e0622256a'
down_revision = 'aba4625da5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_settings_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'site_settings', ['site_settings_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('site_settings_id')

    # ### end Alembic commands ###
