"""Initial migration with current models options update img refresh

Revision ID: 4c58a08eed52
Revises: fdaf858b7378
Create Date: 2025-01-29 11:49:04.549798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c58a08eed52'
down_revision = 'fdaf858b7378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_option_association', schema=None) as batch_op:
        batch_op.create_index('idx_product_option_association_oid_pid', ['option_id', 'product_id'], unique=False)

    with op.batch_alter_table('product_option_value_association', schema=None) as batch_op:
        batch_op.create_index('idx_product_option_value_association_ovid_pid', ['option_value_id', 'product_id'], unique=False)

    with op.batch_alter_table('product_option_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_option_values_option_id'), ['option_id'], unique=False)

    with op.batch_alter_table('product_variation_option_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variation_option_values_option_value_id'), ['option_value_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variation_option_values_variation_id'), ['variation_id'], unique=False)

    with op.batch_alter_table('product_variations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variations_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variations_product_id'))

    with op.batch_alter_table('product_variation_option_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variation_option_values_variation_id'))
        batch_op.drop_index(batch_op.f('ix_product_variation_option_values_option_value_id'))

    with op.batch_alter_table('product_option_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_option_values_option_id'))

    with op.batch_alter_table('product_option_value_association', schema=None) as batch_op:
        batch_op.drop_index('idx_product_option_value_association_ovid_pid')

    with op.batch_alter_table('product_option_association', schema=None) as batch_op:
        batch_op.drop_index('idx_product_option_association_oid_pid')

    # ### end Alembic commands ###
