"""Add video_url to MenuItemExtended

Revision ID: 4fc7af82dbc6
Revises: abc123def456
Create Date: 2025-07-24 18:25:51.798479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc7af82dbc6'
down_revision = 'abc123def456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items_extended', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items_extended', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
