"""Add selected_options to CartItem

Revision ID: 55a681c91e2b
Revises: 364945993833
Create Date: 2025-08-06 10:43:40.036980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a681c91e2b'
down_revision = '364945993833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_options', sa.Text(), nullable=True))

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'menus', ['menu_id'], ['id'])
        batch_op.create_foreign_key(None, 'menu_items', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('selected_options')

    # ### end Alembic commands ###
