"""Add ProductOptionValueImage table for option value photos

Revision ID: 6f34ae9fa062
Revises: 2e33f57d70a4
Create Date: 2025-07-23 18:51:48.467516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f34ae9fa062'
down_revision = '2e33f57d70a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_option_value_images',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('option_value_id', sa.Integer(), nullable=False),
        sa.Column('image_id', sa.Integer(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=True),
        sa.Column('is_main', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
        sa.ForeignKeyConstraint(['option_value_id'], ['product_option_values.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_option_value_image', 'product_option_value_images', ['option_value_id', 'image_id'], unique=False)
    op.create_index(op.f('ix_product_option_value_images_option_value_id'), 'product_option_value_images', ['option_value_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_option_value_images_option_value_id'), table_name='product_option_value_images')
    op.drop_index('idx_option_value_image', table_name='product_option_value_images')
    op.drop_table('product_option_value_images')
    # ### end Alembic commands ###
