"""Initial migration with current models gallery

Revision ID: 8b863edc7f32
Revises: e5574b3abce1
Create Date: 2025-01-30 21:39:45.159524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b863edc7f32'
down_revision = 'e5574b3abce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_instance_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['module_instance_id'], ['module_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_instances_module_instance_id'), ['module_instance_id'], unique=False)

    op.create_table('gallery_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery_instances.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_items_gallery_id'), ['gallery_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_items_gallery_id'))

    op.drop_table('gallery_items')
    with op.batch_alter_table('gallery_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_instances_module_instance_id'))

    op.drop_table('gallery_instances')
    # ### end Alembic commands ###
