"""Initial migration with current models options update

Revision ID: 922b9e32e9f6
Revises: fbd66e05c471
Create Date: 2025-01-28 15:02:42.071538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '922b9e32e9f6'
down_revision = 'fbd66e05c471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variations', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variations', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('sku',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
