"""Initial migration with current models Site settings

Revision ID: 92b0c5701192
Revises: 427e0622256a
Create Date: 2025-02-06 18:08:30.227825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92b0c5701192'
down_revision = '427e0622256a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.drop_constraint('social_links_ibfk_2', type_='foreignkey')
        batch_op.drop_column('site_settings_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_settings_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('social_links_ibfk_2', 'site_settings', ['site_settings_id'], ['id'])

    # ### end Alembic commands ###
