"""Home-page flag

Revision ID: 9afaebf4c1b8
Revises: 3e52a4651772
Create Date: 2025-03-25 17:39:39.390348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9afaebf4c1b8'
down_revision = '3e52a4651772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_page', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('home_page')

    # ### end Alembic commands ###
