"""Initial migration with current models posts2

Revision ID: 9b55d61c8e56
Revises: 6c6344989eb2
Create Date: 2025-02-03 14:32:20.846019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b55d61c8e56'
down_revision = '6c6344989eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_categories', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
