"""Add has_individual_photos to ProductOption

Revision ID: a34bb4914793
Revises: 9afaebf4c1b8
Create Date: 2025-07-23 18:07:09.330236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34bb4914793'
down_revision = '9afaebf4c1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_individual_photos', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.drop_column('has_individual_photos')

    # ### end Alembic commands ###
