"""Initial migration with current models Site settings

Revision ID: aba4625da5f1
Revises: f3c36d52e021
Create Date: 2025-02-06 12:33:50.739763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aba4625da5f1'
down_revision = 'f3c36d52e021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_page_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pages', ['home_page_id'], ['id'])
        batch_op.drop_column('social_links')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_links', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('home_page_id')

    op.drop_table('social_links')
    # ### end Alembic commands ###
