"""Add menu module tables

Revision ID: abc123def456
Revises: 6f34ae9fa062
Create Date: 2024-12-21 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abc123def456'
down_revision = '6f34ae9fa062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Создаем таблицу menu_instances
    op.create_table('menu_instances',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('module_instance_id', sa.Integer(), nullable=False),
        sa.Column('menu_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('show_icons', sa.Boolean(), nullable=True),
        sa.Column('max_depth', sa.Integer(), nullable=True),
        sa.Column('enable_videos', sa.Boolean(), nullable=True),
        sa.Column('menu_style', sa.String(length=50), nullable=True),
        sa.Column('enable_auto_catalog', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
        sa.ForeignKeyConstraint(['module_instance_id'], ['module_instances.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_instances_module_instance_id'), ['module_instance_id'], unique=False)

    # Создаем таблицу menu_items_extended
    op.create_table('menu_items_extended',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('menu_instance_id', sa.Integer(), nullable=False),
        sa.Column('menu_item_id', sa.Integer(), nullable=False),
        sa.Column('item_type', sa.Enum('page', 'category', 'post_category', 'post', 'external', 'catalog', 'custom', name='menu_item_types'), nullable=False),
        sa.Column('target_id', sa.Integer(), nullable=True),
        sa.Column('icon_id', sa.Integer(), nullable=True),
        sa.Column('video_id', sa.Integer(), nullable=True),
        sa.Column('show_in_catalog', sa.Boolean(), nullable=True),
        sa.Column('custom_class', sa.String(length=100), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('open_in_new_tab', sa.Boolean(), nullable=True),
        sa.Column('is_featured', sa.Boolean(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['icon_id'], ['images.id'], ),
        sa.ForeignKeyConstraint(['menu_instance_id'], ['menu_instances.id'], ),
        sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
        sa.ForeignKeyConstraint(['video_id'], ['images.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_items_extended', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_items_extended_menu_instance_id'), ['menu_instance_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items_extended', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_items_extended_menu_instance_id'))

    op.drop_table('menu_items_extended')
    
    with op.batch_alter_table('menu_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_instances_module_instance_id'))

    op.drop_table('menu_instances')
    # ### end Alembic commands ### 