"""Initial migration with current models product_tabs

Revision ID: b8ce206d5460
Revises: 8b863edc7f32
Create Date: 2025-01-30 22:16:23.935169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ce206d5460'
down_revision = '8b863edc7f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabs_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_instance_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['module_instance_id'], ['module_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tabs_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tabs_instances_module_instance_id'), ['module_instance_id'], unique=False)

    op.create_table('tabs_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tabs_id', sa.Integer(), nullable=False),
    sa.Column('tab_title', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('limit_count', sa.Integer(), nullable=True),
    sa.Column('product_ids', sa.Text(), nullable=True),
    sa.Column('button_text', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['tabs_id'], ['tabs_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tabs_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tabs_items_tabs_id'), ['tabs_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabs_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tabs_items_tabs_id'))

    op.drop_table('tabs_items')
    with op.batch_alter_table('tabs_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tabs_instances_module_instance_id'))

    op.drop_table('tabs_instances')
    # ### end Alembic commands ###
