"""Initial migration with current models image order

Revision ID: bbd4c1cf2dee
Revises: f8750f78861f
Create Date: 2025-01-29 19:08:06.683739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd4c1cf2dee'
down_revision = 'f8750f78861f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
