"""Initial migration with current models Pages

Revision ID: e5574b3abce1
Revises: f22caad446c7
Create Date: 2025-01-30 17:18:42.786535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5574b3abce1'
down_revision = 'f22caad446c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_layout',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('col_index', sa.Integer(), nullable=False),
    sa.Column('col_width', sa.Integer(), nullable=False),
    sa.Column('module_instance_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_instance_id'], ['module_instances.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('is_homepage')
        batch_op.drop_column('content')
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_homepage', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('meta_title')

    op.drop_table('page_layout')
    # ### end Alembic commands ###
