"""Initial migration with current models Module Slider

Revision ID: f0c1662b720d
Revises: 0a99b7a1d545
Create Date: 2025-01-30 09:15:15.026157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c1662b720d'
down_revision = '0a99b7a1d545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slider_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_instance_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('transition_type', sa.Enum('fade', 'slide', name='transition_types'), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('show_arrows', sa.Boolean(), nullable=True),
    sa.Column('show_indicators', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['module_instance_id'], ['module_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slider_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slider_instances_module_instance_id'), ['module_instance_id'], unique=False)

    op.create_table('slider_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slider_id', sa.Integer(), nullable=False),
    sa.Column('image_pc_id', sa.Integer(), nullable=False),
    sa.Column('image_mobile_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link_text', sa.String(length=255), nullable=True),
    sa.Column('link_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['image_mobile_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['image_pc_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['slider_id'], ['slider_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slider_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slider_items_slider_id'), ['slider_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slider_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slider_items_slider_id'))

    op.drop_table('slider_items')
    with op.batch_alter_table('slider_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slider_instances_module_instance_id'))

    op.drop_table('slider_instances')
    # ### end Alembic commands ###
