"""Initial migration with current models Modules Slider

Revision ID: f22caad446c7
Revises: f0c1662b720d
Create Date: 2025-01-30 09:43:50.595473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22caad446c7'
down_revision = 'f0c1662b720d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_template', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('creation_template')

    # ### end Alembic commands ###
