"""Initial migration with current models Site settings

Revision ID: f3c36d52e021
Revises: 775a176d5593
Create Date: 2025-02-04 19:11:41.997443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3c36d52e021'
down_revision = '775a176d5593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('site_settings_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'images', ['logo_id'], ['id'])
        batch_op.drop_column('logo')
        batch_op.drop_column('home_page_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_page_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('logo', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('site_settings_ibfk_1', 'pages', ['home_page_id'], ['id'])
        batch_op.drop_column('logo_id')

    # ### end Alembic commands ###
