"""Initial migration with current models options update img refresh2 keys

Revision ID: f8750f78861f
Revises: 4c58a08eed52
Create Date: 2025-01-29 17:51:42.726145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8750f78861f'
down_revision = '4c58a08eed52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seo_keys', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variations', schema=None) as batch_op:
        batch_op.drop_column('seo_keys')

    # ### end Alembic commands ###
