"""Initial migration with current models options

Revision ID: fbd66e05c471
Revises: a48be2f8a779
Create Date: 2025-01-27 19:58:33.756689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd66e05c471'
down_revision = 'a48be2f8a779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_type', sa.String(length=50), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_options_name'), ['name'], unique=False)

    op.create_table('product_option_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['product_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_option_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_option_values_value'), ['value'], unique=False)

    op.create_table('product_option_association',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['product_options.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'option_id')
    )
    with op.batch_alter_table('product_option_association', schema=None) as batch_op:
        batch_op.create_index('idx_product_option_association_pid_oid', ['product_id', 'option_id'], unique=False)

    op.create_table('product_option_value_association',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('option_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_value_id'], ['product_option_values.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'option_value_id')
    )
    with op.batch_alter_table('product_option_value_association', schema=None) as batch_op:
        batch_op.create_index('idx_product_option_value_association_pid_ovid', ['product_id', 'option_value_id'], unique=False)

    op.create_table('product_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variations_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_variations_slug'), ['slug'], unique=True)

    op.create_table('product_variation_option_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.Column('option_value_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_value_id'], ['product_option_values.id'], ),
    sa.ForeignKeyConstraint(['variation_id'], ['product_variations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variation_option_values', schema=None) as batch_op:
        batch_op.create_index('idx_variation_option_value', ['variation_id', 'option_value_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variation_option_values', schema=None) as batch_op:
        batch_op.drop_index('idx_variation_option_value')

    op.drop_table('product_variation_option_values')
    with op.batch_alter_table('product_variations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variations_slug'))
        batch_op.drop_index(batch_op.f('ix_product_variations_sku'))

    op.drop_table('product_variations')
    with op.batch_alter_table('product_option_value_association', schema=None) as batch_op:
        batch_op.drop_index('idx_product_option_value_association_pid_ovid')

    op.drop_table('product_option_value_association')
    with op.batch_alter_table('product_option_association', schema=None) as batch_op:
        batch_op.drop_index('idx_product_option_association_pid_oid')

    op.drop_table('product_option_association')
    with op.batch_alter_table('product_option_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_option_values_value'))

    op.drop_table('product_option_values')
    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_options_name'))

    op.drop_table('product_options')
    # ### end Alembic commands ###
